inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  TargetRubyVersion: 2.6
  SuggestExtensions: false
  NewCops: enable

require:
  - rubocop-performance
  - rubocop-minitest
  - rubocop-rake

Bundler/OrderedGems:
  Enabled: true
