inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  TargetRubyVersion: 4.0
  SuggestExtensions: false
  NewCops: enable

plugins:
  - rubocop-performance
  - rubocop-minitest
  - rubocop-rake

Bundler/OrderedGems:
  Enabled: true
